import { afterEach, expect, test } from "bun:test"
import { Database } from "bun:sqlite"
import { TestServer } from "./support/test-server"
import { Tracker, TrackerController } from "../omarchy/tracker"
import { stat } from "node:fs/promises"
import { join } from "node:path"

let server: TestServer | undefined
afterEach(async () => {
	await server?.close()
	server = undefined
})

test("personal API keys authenticate, hide secrets, enforce ownership and revoke immediately", async () => {
	server = await TestServer.start()
	const created = await server.call<any>("/api/auth/api-keys", { method: "POST", body: { name: "Toolbar" } })
	expect(created.response.status).toBe(201)
	expect(created.response.headers.get("cache-control")).toBe("no-store")
	expect(created.body.key).toMatch(/^pupler_[A-Za-z0-9_-]{43}$/)
	expect(created.body.key_hash).toBeUndefined()
	const { key, id } = created.body
	const headers = { Authorization: `Bearer ${key}`, Cookie: "" }
	const session = await server.call<any>("/api/auth/session", { headers })
	expect(session.response.status).toBe(200)
	expect(session.body.user.username).toBe("test")
	const listed = await server.call<any[]>("/api/auth/api-keys")
	expect(listed.body).toHaveLength(1)
	expect(listed.body[0].key).toBeUndefined()
	expect(listed.body[0].key_hash).toBeUndefined()
	expect(listed.body[0].last_used_at).toBeString()
	const db = new Database(server.dbPath, { readonly: true })
	try {
		const stored = db.query("SELECT key_hash FROM user_api_keys WHERE id = ?").get(id) as { key_hash: string }
		expect(stored.key_hash).toMatch(/^[a-f0-9]{64}$/)
		expect(stored.key_hash).not.toBe(key)
	} finally { db.close() }
	expect((await server.call("/api/auth/api-keys", { headers })).response.status).toBe(403)
	expect((await server.call("/api/auth/api-keys", { method: "POST", headers, body: { name: "Child" } })).response.status).toBe(403)
	expect((await server.call("/api/auth/session", { headers: { Authorization: "Bearer invalid" } })).response.status).toBe(401)
	expect((await server.call("/api/auth/api-keys", { method: "POST", body: { name: " " } })).response.status).toBe(400)
	await server.call("/api/users", { method: "POST", body: { name: "Other", username: "other", password: "other-password", is_admin: false } })
	const login = await server.call("/api/auth/login", { method: "POST", body: { username: "other", password: "other-password" } })
	const otherCookie = login.response.headers.get("set-cookie")!.split(";")[0]!
	const other = { Cookie: otherCookie }
	expect((await server.call<any[]>("/api/auth/api-keys", { headers: other })).body).toHaveLength(0)
	expect((await server.call(`/api/auth/api-keys/${id}`, { method: "DELETE", headers: other })).response.status).toBe(404)
	const otherKey = await server.call<any>("/api/auth/api-keys", { method: "POST", headers: other, body: { name: "Personal" } })
	expect(otherKey.response.status).toBe(201)
	expect((await server.call("/api/users", { headers: { Authorization: `Bearer ${otherKey.body.key}`, Cookie: "" } })).response.status).toBe(403)
	expect((await server.call(`/api/auth/api-keys/${id}`, { method: "DELETE" })).response.status).toBe(204)
	expect((await server.call("/api/auth/session", { headers })).response.status).toBe(401)
}, 20000)

test("toolbar reads and stops its user's timer, rejects changed timers and missing projects", async () => {
	server = await TestServer.start()
	const created = await server.call<any>("/api/auth/api-keys", { method: "POST", body: { name: "Toolbar" } })
	const tracker = new Tracker({ baseUrl: server.baseUrl, apiKey: created.body.key })
	expect(await tracker.current()).toBeNull()
	const user = await server.call<any>("/api/auth/session")
	const project = await server.call<any>("/api/projects", { method: "POST", body: { name: "Toolbar test" } })
	expect(project.response.status).toBe(201)
	const started = await server.call<any>("/api/time-entries/start", { method: "POST", body: { user_id: user.body.user.id, project_id: project.body.id, description: "Testing toolbar", started_at: "2026-01-01T00:00:00.000Z" } })
	expect(started.response.status).toBe(201)
	expect((await tracker.current())?.id).toBe(started.body.id)
	await expect(tracker.stop(started.body.id + 1)).rejects.toThrow("Timer changed")
	await tracker.stop(started.body.id)
	expect(await tracker.current()).toBeNull()
	const stopped = await server.call<any>(`/api/time-entries/${started.body.id}`)
	expect(stopped.body.ended_at).toBeString()
	const unassigned = await server.call<any>("/api/time-entries/start", { method: "POST", body: { user_id: user.body.user.id } })
	await expect(tracker.stop(unassigned.body.id)).rejects.toThrow("Choose a project")
	await server.call(`/api/auth/api-keys/${created.body.id}`, { method: "DELETE" })
	await expect(tracker.current()).rejects.toThrow("API key rejected")
}, 20000)

test("toolbar setup validates and saves a private key, survives restart and prompts after revocation", async () => {
	server = await TestServer.start()
	const path = join(server.tempDir, "config", "omarchy.json")
	const controller = new TrackerController(path)
	expect((await controller.handle({ action: "status" })).needsConfig).toBe(true)
	const invalid = await controller.handle({ action: "configure", baseUrl: server.baseUrl, apiKey: "bad" })
	expect(invalid.needsConfig).toBe(true)
	expect(await Bun.file(path).exists()).toBe(false)
	const created = await server.call<any>("/api/auth/api-keys", { method: "POST", body: { name: "Setup" } })
	const configured = await controller.handle({ action: "configure", baseUrl: server.baseUrl, apiKey: created.body.key })
	expect(configured.error).toBe("")
	expect(configured.needsConfig).toBe(false)
	expect(JSON.stringify(configured)).not.toContain(created.body.key)
	expect((await stat(path)).mode & 0o777).toBe(0o600)
	expect((await new TrackerController(path).handle({ action: "status" })).needsConfig).toBe(false)
	const rejected = await controller.handle({ action: "configure", baseUrl: server.baseUrl, apiKey: `pupler_${"a".repeat(43)}` })
	expect(rejected.needsConfig).toBe(true)
	expect((await Bun.file(path).json()).apiKey).toBe(created.body.key)
	await server.call(`/api/auth/api-keys/${created.body.id}`, { method: "DELETE" })
	expect((await controller.handle({ action: "status" })).needsConfig).toBe(true)
}, 20000)

test("toolbar starts and stops timers with an active project and preserves existing timers", async () => {
	server = await TestServer.start()
	const key = await server.call<any>("/api/auth/api-keys", { method: "POST", body: { name: "Start timer" } })
	const controller = new TrackerController(join(server.tempDir, "toolbar.json"))
	await controller.handle({ action: "configure", baseUrl: server.baseUrl, apiKey: key.body.key })
	const project = await server.call<any>("/api/projects", { method: "POST", body: { name: "Active" } })
	const archived = await server.call<any>("/api/projects", { method: "POST", body: { name: "Archived", archived_at: "2026-01-01T00:00:00.000Z" } })
	const status = await controller.handle({ action: "status", includeProjects: true })
	expect(status.projects?.map(project => project.id)).toEqual([project.body.id])
	expect((await controller.handle({ action: "start" })).error).toContain("Choose a project")
	expect((await controller.handle({ action: "start", projectId: archived.body.id })).error).toContain("unavailable")
	const started = await controller.handle({ action: "start", projectId: project.body.id, description: "  Toolbar task  " })
	expect(started.error).toBe("")
	expect(started.entry?.project_id).toBe(project.body.id)
	expect(started.entry?.description).toBe("Toolbar task")
	const session = await server.call<any>("/api/auth/session")
	expect(started.entry?.user_id).toBe(session.body.user.id)
	const duplicate = await controller.handle({ action: "start", projectId: project.body.id })
	expect(duplicate.error).toContain("already running")
	expect((await controller.handle({ action: "status" })).entry?.id).toBe(started.entry!.id)
	const stopped = await controller.handle({ action: "stop", id: started.entry!.id })
	expect(stopped.error).toBe("")
	expect(stopped.entry).toBeNull()
	const blank = await controller.handle({ action: "start", projectId: project.body.id })
	expect(blank.error).toBe("")
	expect(blank.entry?.description).toBeNull()
	const unassigned = new Tracker({ baseUrl: server.baseUrl, apiKey: key.body.key, userId: null })
	const other = await unassigned.start(project.body.id, "Unassigned")
	expect(other.user_id).toBeNull()
	expect((await controller.handle({ action: "status" })).entry?.id).toBe(blank.entry!.id)
}, 20000)

test("toolbar creates a project and can immediately use it for a timer", async () => {
	server = await TestServer.start()
	const key = await server.call<any>("/api/auth/api-keys", { method: "POST", body: { name: "Create project" } })
	const controller = new TrackerController(join(server.tempDir, "toolbar.json"))
	await controller.handle({ action: "configure", baseUrl: server.baseUrl, apiKey: key.body.key })
	const invalid = await controller.handle({ action: "create-project", projectName: " \n " })
	expect(invalid.error).toBe("Enter a project name.")
	expect((await controller.handle({ action: "status", includeProjects: true })).projects).toEqual([])
	const created = await controller.handle({ action: "create-project", projectName: "  New toolbar project  " })
	expect(created.error).toBe("")
	expect(created.createdProject?.name).toBe("New toolbar project")
	expect(created.createdProject?.archived_at).toBeNull()
	const status = await controller.handle({ action: "status", includeProjects: true })
	expect(status.entry).toBeNull()
	expect(status.projects?.map(project => project.id)).toContain(created.createdProject!.id)
	const started = await controller.handle({ action: "start", projectId: created.createdProject!.id })
	expect(started.error).toBe("")
	expect(started.entry?.project_id).toBe(created.createdProject!.id)
	expect((await controller.handle({ action: "stop", id: started.entry!.id })).error).toBe("")
	await server.call(`/api/auth/api-keys/${key.body.id}`, { method: "DELETE" })
	const revoked = await controller.handle({ action: "create-project", projectName: "Rejected" })
	expect(revoked.needsConfig).toBe(true)
	expect(revoked.createdProject).toBeUndefined()
	expect((await server.call<any[]>("/api/projects")).body).toHaveLength(1)
}, 20000)
